/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Cryptokey
 */
public class CryptokeyTest {
    private final Cryptokey model = new Cryptokey();

    /**
     * Model tests for Cryptokey
     */
    @Test
    public void testCryptokey() {
        // TODO: test Cryptokey
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'keytype'
     */
    @Test
    public void keytypeTest() {
        // TODO: test keytype
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'published'
     */
    @Test
    public void publishedTest() {
        // TODO: test published
    }

    /**
     * Test the property 'dnskey'
     */
    @Test
    public void dnskeyTest() {
        // TODO: test dnskey
    }

    /**
     * Test the property 'ds'
     */
    @Test
    public void dsTest() {
        // TODO: test ds
    }

    /**
     * Test the property 'privatekey'
     */
    @Test
    public void privatekeyTest() {
        // TODO: test privatekey
    }

    /**
     * Test the property 'algorithm'
     */
    @Test
    public void algorithmTest() {
        // TODO: test algorithm
    }

    /**
     * Test the property 'bits'
     */
    @Test
    public void bitsTest() {
        // TODO: test bits
    }

}
