/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RRSet;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Zone
 */
public class ZoneTest {
    private final Zone model = new Zone();

    /**
     * Model tests for Zone
     */
    @Test
    public void testZone() {
        // TODO: test Zone
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'rrsets'
     */
    @Test
    public void rrsetsTest() {
        // TODO: test rrsets
    }

    /**
     * Test the property 'serial'
     */
    @Test
    public void serialTest() {
        // TODO: test serial
    }

    /**
     * Test the property 'notifiedSerial'
     */
    @Test
    public void notifiedSerialTest() {
        // TODO: test notifiedSerial
    }

    /**
     * Test the property 'editedSerial'
     */
    @Test
    public void editedSerialTest() {
        // TODO: test editedSerial
    }

    /**
     * Test the property 'masters'
     */
    @Test
    public void mastersTest() {
        // TODO: test masters
    }

    /**
     * Test the property 'dnssec'
     */
    @Test
    public void dnssecTest() {
        // TODO: test dnssec
    }

    /**
     * Test the property 'nsec3param'
     */
    @Test
    public void nsec3paramTest() {
        // TODO: test nsec3param
    }

    /**
     * Test the property 'nsec3narrow'
     */
    @Test
    public void nsec3narrowTest() {
        // TODO: test nsec3narrow
    }

    /**
     * Test the property 'presigned'
     */
    @Test
    public void presignedTest() {
        // TODO: test presigned
    }

    /**
     * Test the property 'soaEdit'
     */
    @Test
    public void soaEditTest() {
        // TODO: test soaEdit
    }

    /**
     * Test the property 'soaEditApi'
     */
    @Test
    public void soaEditApiTest() {
        // TODO: test soaEditApi
    }

    /**
     * Test the property 'apiRectify'
     */
    @Test
    public void apiRectifyTest() {
        // TODO: test apiRectify
    }

    /**
     * Test the property 'zone'
     */
    @Test
    public void zoneTest() {
        // TODO: test zone
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'nameservers'
     */
    @Test
    public void nameserversTest() {
        // TODO: test nameservers
    }

    /**
     * Test the property 'masterTsigKeyIds'
     */
    @Test
    public void masterTsigKeyIdsTest() {
        // TODO: test masterTsigKeyIds
    }

    /**
     * Test the property 'slaveTsigKeyIds'
     */
    @Test
    public void slaveTsigKeyIdsTest() {
        // TODO: test slaveTsigKeyIds
    }

}
