/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ConfigSetting;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConfigApi
 */
@Ignore
public class ConfigApiTest {

    private final ConfigApi api = new ConfigApi();

    
    /**
     * Returns all ConfigSettings for a single server
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConfigTest() throws ApiException {
        String serverId = null;
        List<ConfigSetting> response = api.getConfig(serverId);

        // TODO: test validations
    }
    
    /**
     * Returns a specific ConfigSetting for a single server
     *
     * NOT IMPLEMENTED
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConfigSettingTest() throws ApiException {
        String serverId = null;
        String configSettingName = null;
        ConfigSetting response = api.getConfigSetting(serverId, configSettingName);

        // TODO: test validations
    }
    
}
