/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatsApi
 */
@Ignore
public class StatsApiTest {

    private final StatsApi api = new StatsApi();

    
    /**
     * Query statistics.
     *
     * Query PowerDNS internal statistics.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatsTest() throws ApiException {
        String serverId = null;
        String statistic = null;
        Boolean includerings = null;
        List<Object> response = api.getStats(serverId, statistic, includerings);

        // TODO: test validations
    }
    
}
