/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.TSIGKey;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TsigkeyApi
 */
@Ignore
public class TsigkeyApiTest {

    private final TsigkeyApi api = new TsigkeyApi();

    
    /**
     * Add a TSIG key
     *
     * This methods add a new TSIGKey. The actual key can be generated by the server or be provided by the client
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTSIGKeyTest() throws ApiException {
        String serverId = null;
        TSIGKey tsigkey = null;
        TSIGKey response = api.createTSIGKey(serverId, tsigkey);

        // TODO: test validations
    }
    
    /**
     * Delete the TSIGKey with tsigkey_id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTSIGKeyTest() throws ApiException {
        String serverId = null;
        String tsigkeyId = null;
        api.deleteTSIGKey(serverId, tsigkeyId);

        // TODO: test validations
    }
    
    /**
     * Get a specific TSIGKeys on the server, including the actual key
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTSIGKeyTest() throws ApiException {
        String serverId = null;
        String tsigkeyId = null;
        TSIGKey response = api.getTSIGKey(serverId, tsigkeyId);

        // TODO: test validations
    }
    
    /**
     * Get all TSIGKeys on the server, except the actual key
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTSIGKeysTest() throws ApiException {
        String serverId = null;
        List<TSIGKey> response = api.listTSIGKeys(serverId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * The TSIGKey at tsigkey_id can be changed in multiple ways:  * Changing the Name, this will remove the key with tsigkey_id after adding.  * Changing the Algorithm  * Changing the Key Only the relevant fields have to be provided in the request body. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putTSIGKeyTest() throws ApiException {
        String serverId = null;
        String tsigkeyId = null;
        TSIGKey tsigkey = null;
        TSIGKey response = api.putTSIGKey(serverId, tsigkeyId, tsigkey);

        // TODO: test validations
    }
    
}
