/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Metadata;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ZonemetadataApi
 */
@Ignore
public class ZonemetadataApiTest {

    private final ZonemetadataApi api = new ZonemetadataApi();

    
    /**
     * Creates a set of metadata entries
     *
     * Creates a set of metadata entries of given kind for the zone. Existing metadata entries for the zone with the same kind are not overwritten.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createMetadataTest() throws ApiException {
        String serverId = null;
        String zoneId = null;
        Metadata metadata = null;
        api.createMetadata(serverId, zoneId, metadata);

        // TODO: test validations
    }
    
    /**
     * Delete all items of a single kind of domain metadata.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteMetadataTest() throws ApiException {
        String serverId = null;
        String zoneId = null;
        String metadataKind = null;
        api.deleteMetadata(serverId, zoneId, metadataKind);

        // TODO: test validations
    }
    
    /**
     * Get the content of a single kind of domain metadata as a Metadata object.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMetadataTest() throws ApiException {
        String serverId = null;
        String zoneId = null;
        String metadataKind = null;
        Metadata response = api.getMetadata(serverId, zoneId, metadataKind);

        // TODO: test validations
    }
    
    /**
     * Get all the Metadata associated with the zone.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listMetadataTest() throws ApiException {
        String serverId = null;
        String zoneId = null;
        List<Metadata> response = api.listMetadata(serverId, zoneId);

        // TODO: test validations
    }
    
    /**
     * Replace the content of a single kind of domain metadata.
     *
     * Creates a set of metadata entries of given kind for the zone. Existing metadata entries for the zone with the same kind are removed.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modifyMetadataTest() throws ApiException {
        String serverId = null;
        String zoneId = null;
        String metadataKind = null;
        Metadata metadata = null;
        Metadata response = api.modifyMetadata(serverId, zoneId, metadataKind, metadata);

        // TODO: test validations
    }
    
}
