/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Server
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-27T14:59:34.966+02:00[Europe/Paris]")
public class Server {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_DAEMON_TYPE = "daemon_type";
  @SerializedName(SERIALIZED_NAME_DAEMON_TYPE)
  private String daemonType;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_CONFIG_URL = "config_url";
  @SerializedName(SERIALIZED_NAME_CONFIG_URL)
  private String configUrl;

  public static final String SERIALIZED_NAME_ZONES_URL = "zones_url";
  @SerializedName(SERIALIZED_NAME_ZONES_URL)
  private String zonesUrl;


  public Server type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Set to “Server”
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set to “Server”")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public Server id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id of the server, “localhost”
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id of the server, “localhost”")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Server daemonType(String daemonType) {
    
    this.daemonType = daemonType;
    return this;
  }

   /**
   * “recursor” for the PowerDNS Recursor and “authoritative” for the Authoritative Server
   * @return daemonType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "“recursor” for the PowerDNS Recursor and “authoritative” for the Authoritative Server")

  public String getDaemonType() {
    return daemonType;
  }


  public void setDaemonType(String daemonType) {
    this.daemonType = daemonType;
  }


  public Server version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * The version of the server software
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The version of the server software")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public Server url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * The API endpoint for this server
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The API endpoint for this server")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public Server configUrl(String configUrl) {
    
    this.configUrl = configUrl;
    return this;
  }

   /**
   * The API endpoint for this server’s configuration
   * @return configUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The API endpoint for this server’s configuration")

  public String getConfigUrl() {
    return configUrl;
  }


  public void setConfigUrl(String configUrl) {
    this.configUrl = configUrl;
  }


  public Server zonesUrl(String zonesUrl) {
    
    this.zonesUrl = zonesUrl;
    return this;
  }

   /**
   * The API endpoint for this server’s zones
   * @return zonesUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The API endpoint for this server’s zones")

  public String getZonesUrl() {
    return zonesUrl;
  }


  public void setZonesUrl(String zonesUrl) {
    this.zonesUrl = zonesUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Server server = (Server) o;
    return Objects.equals(this.type, server.type) &&
        Objects.equals(this.id, server.id) &&
        Objects.equals(this.daemonType, server.daemonType) &&
        Objects.equals(this.version, server.version) &&
        Objects.equals(this.url, server.url) &&
        Objects.equals(this.configUrl, server.configUrl) &&
        Objects.equals(this.zonesUrl, server.zonesUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, id, daemonType, version, url, configUrl, zonesUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Server {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    daemonType: ").append(toIndentedString(daemonType)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    configUrl: ").append(toIndentedString(configUrl)).append("\n");
    sb.append("    zonesUrl: ").append(toIndentedString(zonesUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

