/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RRSet;

/**
 * This represents an authoritative DNS Zone.
 */
@ApiModel(description = "This represents an authoritative DNS Zone.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-27T14:59:34.966+02:00[Europe/Paris]")
public class Zone {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  /**
   * Zone kind, one of “Native”, “Master”, “Slave”
   */
  @JsonAdapter(KindEnum.Adapter.class)
  public enum KindEnum {
    NATIVE("Native"),
    
    MASTER("Master"),
    
    SLAVE("Slave");

    private String value;

    KindEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static KindEnum fromValue(String value) {
      for (KindEnum b : KindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<KindEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final KindEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public KindEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return KindEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private KindEnum kind;

  public static final String SERIALIZED_NAME_RRSETS = "rrsets";
  @SerializedName(SERIALIZED_NAME_RRSETS)
  private List<RRSet> rrsets = null;

  public static final String SERIALIZED_NAME_SERIAL = "serial";
  @SerializedName(SERIALIZED_NAME_SERIAL)
  private Integer serial;

  public static final String SERIALIZED_NAME_NOTIFIED_SERIAL = "notified_serial";
  @SerializedName(SERIALIZED_NAME_NOTIFIED_SERIAL)
  private Integer notifiedSerial;

  public static final String SERIALIZED_NAME_EDITED_SERIAL = "edited_serial";
  @SerializedName(SERIALIZED_NAME_EDITED_SERIAL)
  private Integer editedSerial;

  public static final String SERIALIZED_NAME_MASTERS = "masters";
  @SerializedName(SERIALIZED_NAME_MASTERS)
  private List<String> masters = null;

  public static final String SERIALIZED_NAME_DNSSEC = "dnssec";
  @SerializedName(SERIALIZED_NAME_DNSSEC)
  private Boolean dnssec;

  public static final String SERIALIZED_NAME_NSEC3PARAM = "nsec3param";
  @SerializedName(SERIALIZED_NAME_NSEC3PARAM)
  private String nsec3param;

  public static final String SERIALIZED_NAME_NSEC3NARROW = "nsec3narrow";
  @SerializedName(SERIALIZED_NAME_NSEC3NARROW)
  private Boolean nsec3narrow;

  public static final String SERIALIZED_NAME_PRESIGNED = "presigned";
  @SerializedName(SERIALIZED_NAME_PRESIGNED)
  private Boolean presigned;

  public static final String SERIALIZED_NAME_SOA_EDIT = "soa_edit";
  @SerializedName(SERIALIZED_NAME_SOA_EDIT)
  private String soaEdit;

  public static final String SERIALIZED_NAME_SOA_EDIT_API = "soa_edit_api";
  @SerializedName(SERIALIZED_NAME_SOA_EDIT_API)
  private String soaEditApi;

  public static final String SERIALIZED_NAME_API_RECTIFY = "api_rectify";
  @SerializedName(SERIALIZED_NAME_API_RECTIFY)
  private Boolean apiRectify;

  public static final String SERIALIZED_NAME_ZONE = "zone";
  @SerializedName(SERIALIZED_NAME_ZONE)
  private String zone;

  public static final String SERIALIZED_NAME_ACCOUNT = "account";
  @SerializedName(SERIALIZED_NAME_ACCOUNT)
  private String account;

  public static final String SERIALIZED_NAME_NAMESERVERS = "nameservers";
  @SerializedName(SERIALIZED_NAME_NAMESERVERS)
  private List<String> nameservers = null;

  public static final String SERIALIZED_NAME_MASTER_TSIG_KEY_IDS = "master_tsig_key_ids";
  @SerializedName(SERIALIZED_NAME_MASTER_TSIG_KEY_IDS)
  private List<String> masterTsigKeyIds = null;

  public static final String SERIALIZED_NAME_SLAVE_TSIG_KEY_IDS = "slave_tsig_key_ids";
  @SerializedName(SERIALIZED_NAME_SLAVE_TSIG_KEY_IDS)
  private List<String> slaveTsigKeyIds = null;


  public Zone id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Opaque zone id (string), assigned by the server, should not be interpreted by the application. Guaranteed to be safe for embedding in URLs.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Opaque zone id (string), assigned by the server, should not be interpreted by the application. Guaranteed to be safe for embedding in URLs.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Zone name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the zone (e.g. “example.com.”) MUST have a trailing dot
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the zone (e.g. “example.com.”) MUST have a trailing dot")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Zone type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Set to “Zone”
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set to “Zone”")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public Zone url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * API endpoint for this zone
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "API endpoint for this zone")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public Zone kind(KindEnum kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Zone kind, one of “Native”, “Master”, “Slave”
   * @return kind
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Zone kind, one of “Native”, “Master”, “Slave”")

  public KindEnum getKind() {
    return kind;
  }


  public void setKind(KindEnum kind) {
    this.kind = kind;
  }


  public Zone rrsets(List<RRSet> rrsets) {
    
    this.rrsets = rrsets;
    return this;
  }

  public Zone addRrsetsItem(RRSet rrsetsItem) {
    if (this.rrsets == null) {
      this.rrsets = new ArrayList<RRSet>();
    }
    this.rrsets.add(rrsetsItem);
    return this;
  }

   /**
   * RRSets in this zone (for zones/{zone_id} endpoint only; omitted during GET on the .../zones list endpoint)
   * @return rrsets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "RRSets in this zone (for zones/{zone_id} endpoint only; omitted during GET on the .../zones list endpoint)")

  public List<RRSet> getRrsets() {
    return rrsets;
  }


  public void setRrsets(List<RRSet> rrsets) {
    this.rrsets = rrsets;
  }


  public Zone serial(Integer serial) {
    
    this.serial = serial;
    return this;
  }

   /**
   * The SOA serial number
   * @return serial
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The SOA serial number")

  public Integer getSerial() {
    return serial;
  }


  public void setSerial(Integer serial) {
    this.serial = serial;
  }


  public Zone notifiedSerial(Integer notifiedSerial) {
    
    this.notifiedSerial = notifiedSerial;
    return this;
  }

   /**
   * The SOA serial notifications have been sent out for
   * @return notifiedSerial
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The SOA serial notifications have been sent out for")

  public Integer getNotifiedSerial() {
    return notifiedSerial;
  }


  public void setNotifiedSerial(Integer notifiedSerial) {
    this.notifiedSerial = notifiedSerial;
  }


  public Zone editedSerial(Integer editedSerial) {
    
    this.editedSerial = editedSerial;
    return this;
  }

   /**
   * The SOA serial as seen in query responses. Calculated using the SOA-EDIT metadata, default-soa-edit and default-soa-edit-signed settings
   * @return editedSerial
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The SOA serial as seen in query responses. Calculated using the SOA-EDIT metadata, default-soa-edit and default-soa-edit-signed settings")

  public Integer getEditedSerial() {
    return editedSerial;
  }


  public void setEditedSerial(Integer editedSerial) {
    this.editedSerial = editedSerial;
  }


  public Zone masters(List<String> masters) {
    
    this.masters = masters;
    return this;
  }

  public Zone addMastersItem(String mastersItem) {
    if (this.masters == null) {
      this.masters = new ArrayList<String>();
    }
    this.masters.add(mastersItem);
    return this;
  }

   /**
   *  List of IP addresses configured as a master for this zone (“Slave” type zones only)
   * @return masters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = " List of IP addresses configured as a master for this zone (“Slave” type zones only)")

  public List<String> getMasters() {
    return masters;
  }


  public void setMasters(List<String> masters) {
    this.masters = masters;
  }


  public Zone dnssec(Boolean dnssec) {
    
    this.dnssec = dnssec;
    return this;
  }

   /**
   * Whether or not this zone is DNSSEC signed (inferred from presigned being true XOR presence of at least one cryptokey with active being true)
   * @return dnssec
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not this zone is DNSSEC signed (inferred from presigned being true XOR presence of at least one cryptokey with active being true)")

  public Boolean getDnssec() {
    return dnssec;
  }


  public void setDnssec(Boolean dnssec) {
    this.dnssec = dnssec;
  }


  public Zone nsec3param(String nsec3param) {
    
    this.nsec3param = nsec3param;
    return this;
  }

   /**
   * The NSEC3PARAM record
   * @return nsec3param
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The NSEC3PARAM record")

  public String getNsec3param() {
    return nsec3param;
  }


  public void setNsec3param(String nsec3param) {
    this.nsec3param = nsec3param;
  }


  public Zone nsec3narrow(Boolean nsec3narrow) {
    
    this.nsec3narrow = nsec3narrow;
    return this;
  }

   /**
   * Whether or not the zone uses NSEC3 narrow
   * @return nsec3narrow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not the zone uses NSEC3 narrow")

  public Boolean getNsec3narrow() {
    return nsec3narrow;
  }


  public void setNsec3narrow(Boolean nsec3narrow) {
    this.nsec3narrow = nsec3narrow;
  }


  public Zone presigned(Boolean presigned) {
    
    this.presigned = presigned;
    return this;
  }

   /**
   * Whether or not the zone is pre-signed
   * @return presigned
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not the zone is pre-signed")

  public Boolean getPresigned() {
    return presigned;
  }


  public void setPresigned(Boolean presigned) {
    this.presigned = presigned;
  }


  public Zone soaEdit(String soaEdit) {
    
    this.soaEdit = soaEdit;
    return this;
  }

   /**
   * The SOA-EDIT metadata item
   * @return soaEdit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The SOA-EDIT metadata item")

  public String getSoaEdit() {
    return soaEdit;
  }


  public void setSoaEdit(String soaEdit) {
    this.soaEdit = soaEdit;
  }


  public Zone soaEditApi(String soaEditApi) {
    
    this.soaEditApi = soaEditApi;
    return this;
  }

   /**
   * The SOA-EDIT-API metadata item
   * @return soaEditApi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The SOA-EDIT-API metadata item")

  public String getSoaEditApi() {
    return soaEditApi;
  }


  public void setSoaEditApi(String soaEditApi) {
    this.soaEditApi = soaEditApi;
  }


  public Zone apiRectify(Boolean apiRectify) {
    
    this.apiRectify = apiRectify;
    return this;
  }

   /**
   *  Whether or not the zone will be rectified on data changes via the API
   * @return apiRectify
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = " Whether or not the zone will be rectified on data changes via the API")

  public Boolean getApiRectify() {
    return apiRectify;
  }


  public void setApiRectify(Boolean apiRectify) {
    this.apiRectify = apiRectify;
  }


  public Zone zone(String zone) {
    
    this.zone = zone;
    return this;
  }

   /**
   * MAY contain a BIND-style zone file when creating a zone
   * @return zone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "MAY contain a BIND-style zone file when creating a zone")

  public String getZone() {
    return zone;
  }


  public void setZone(String zone) {
    this.zone = zone;
  }


  public Zone account(String account) {
    
    this.account = account;
    return this;
  }

   /**
   * MAY be set. Its value is defined by local policy
   * @return account
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "MAY be set. Its value is defined by local policy")

  public String getAccount() {
    return account;
  }


  public void setAccount(String account) {
    this.account = account;
  }


  public Zone nameservers(List<String> nameservers) {
    
    this.nameservers = nameservers;
    return this;
  }

  public Zone addNameserversItem(String nameserversItem) {
    if (this.nameservers == null) {
      this.nameservers = new ArrayList<String>();
    }
    this.nameservers.add(nameserversItem);
    return this;
  }

   /**
   * MAY be sent in client bodies during creation, and MUST NOT be sent by the server. Simple list of strings of nameserver names, including the trailing dot. Not required for slave zones.
   * @return nameservers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "MAY be sent in client bodies during creation, and MUST NOT be sent by the server. Simple list of strings of nameserver names, including the trailing dot. Not required for slave zones.")

  public List<String> getNameservers() {
    return nameservers;
  }


  public void setNameservers(List<String> nameservers) {
    this.nameservers = nameservers;
  }


  public Zone masterTsigKeyIds(List<String> masterTsigKeyIds) {
    
    this.masterTsigKeyIds = masterTsigKeyIds;
    return this;
  }

  public Zone addMasterTsigKeyIdsItem(String masterTsigKeyIdsItem) {
    if (this.masterTsigKeyIds == null) {
      this.masterTsigKeyIds = new ArrayList<String>();
    }
    this.masterTsigKeyIds.add(masterTsigKeyIdsItem);
    return this;
  }

   /**
   * The id of the TSIG keys used for master operation in this zone
   * @return masterTsigKeyIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id of the TSIG keys used for master operation in this zone")

  public List<String> getMasterTsigKeyIds() {
    return masterTsigKeyIds;
  }


  public void setMasterTsigKeyIds(List<String> masterTsigKeyIds) {
    this.masterTsigKeyIds = masterTsigKeyIds;
  }


  public Zone slaveTsigKeyIds(List<String> slaveTsigKeyIds) {
    
    this.slaveTsigKeyIds = slaveTsigKeyIds;
    return this;
  }

  public Zone addSlaveTsigKeyIdsItem(String slaveTsigKeyIdsItem) {
    if (this.slaveTsigKeyIds == null) {
      this.slaveTsigKeyIds = new ArrayList<String>();
    }
    this.slaveTsigKeyIds.add(slaveTsigKeyIdsItem);
    return this;
  }

   /**
   * The id of the TSIG keys used for slave operation in this zone
   * @return slaveTsigKeyIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id of the TSIG keys used for slave operation in this zone")

  public List<String> getSlaveTsigKeyIds() {
    return slaveTsigKeyIds;
  }


  public void setSlaveTsigKeyIds(List<String> slaveTsigKeyIds) {
    this.slaveTsigKeyIds = slaveTsigKeyIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Zone zone = (Zone) o;
    return Objects.equals(this.id, zone.id) &&
        Objects.equals(this.name, zone.name) &&
        Objects.equals(this.type, zone.type) &&
        Objects.equals(this.url, zone.url) &&
        Objects.equals(this.kind, zone.kind) &&
        Objects.equals(this.rrsets, zone.rrsets) &&
        Objects.equals(this.serial, zone.serial) &&
        Objects.equals(this.notifiedSerial, zone.notifiedSerial) &&
        Objects.equals(this.editedSerial, zone.editedSerial) &&
        Objects.equals(this.masters, zone.masters) &&
        Objects.equals(this.dnssec, zone.dnssec) &&
        Objects.equals(this.nsec3param, zone.nsec3param) &&
        Objects.equals(this.nsec3narrow, zone.nsec3narrow) &&
        Objects.equals(this.presigned, zone.presigned) &&
        Objects.equals(this.soaEdit, zone.soaEdit) &&
        Objects.equals(this.soaEditApi, zone.soaEditApi) &&
        Objects.equals(this.apiRectify, zone.apiRectify) &&
        Objects.equals(this.zone, zone.zone) &&
        Objects.equals(this.account, zone.account) &&
        Objects.equals(this.nameservers, zone.nameservers) &&
        Objects.equals(this.masterTsigKeyIds, zone.masterTsigKeyIds) &&
        Objects.equals(this.slaveTsigKeyIds, zone.slaveTsigKeyIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, type, url, kind, rrsets, serial, notifiedSerial, editedSerial, masters, dnssec, nsec3param, nsec3narrow, presigned, soaEdit, soaEditApi, apiRectify, zone, account, nameservers, masterTsigKeyIds, slaveTsigKeyIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Zone {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    rrsets: ").append(toIndentedString(rrsets)).append("\n");
    sb.append("    serial: ").append(toIndentedString(serial)).append("\n");
    sb.append("    notifiedSerial: ").append(toIndentedString(notifiedSerial)).append("\n");
    sb.append("    editedSerial: ").append(toIndentedString(editedSerial)).append("\n");
    sb.append("    masters: ").append(toIndentedString(masters)).append("\n");
    sb.append("    dnssec: ").append(toIndentedString(dnssec)).append("\n");
    sb.append("    nsec3param: ").append(toIndentedString(nsec3param)).append("\n");
    sb.append("    nsec3narrow: ").append(toIndentedString(nsec3narrow)).append("\n");
    sb.append("    presigned: ").append(toIndentedString(presigned)).append("\n");
    sb.append("    soaEdit: ").append(toIndentedString(soaEdit)).append("\n");
    sb.append("    soaEditApi: ").append(toIndentedString(soaEditApi)).append("\n");
    sb.append("    apiRectify: ").append(toIndentedString(apiRectify)).append("\n");
    sb.append("    zone: ").append(toIndentedString(zone)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    nameservers: ").append(toIndentedString(nameservers)).append("\n");
    sb.append("    masterTsigKeyIds: ").append(toIndentedString(masterTsigKeyIds)).append("\n");
    sb.append("    slaveTsigKeyIds: ").append(toIndentedString(slaveTsigKeyIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

